### PR TITLE
Fixes #245: Correct broken link for Badgeyay

### LINKED ISSUE #245: Fix broken link for Badgeyay image
Correct the filename

### PR DESCRIPTION
**Pull request by akshatnitd**

### CODE REVIEW

**Comment by ParthS007** [comment]
@akshatnitd Please leave these type of issues for GCI students

**Comment by ParthS007** [comment]
How you merge your on your own and It has not passed Travis even

**Comment by mariobehling** [comment]
@ParthS007 I think Travis is not suitable for this repo as it holds static pages. Honestly, I am merging small improvements myself as well from time to time, which is a bad practice :(

So, as we are working together, yes you are right: Let's ensure quality by reviewing.

**Comment by ParthS007** [comment]
Thanks @mariobehling

**Pull request merged**
