### PR TITLE
Added Responsive back to top button.

### PR DESCRIPTION
**Pull request by Aishh2k**
Pull Request: #338 

Added a **Responsive Back to top button**
 **Preview link:** https://aishh2k.github.io/labs.aishh/
**Before:**
screenshot 49

**After:**
screenshot 50 _li

### CODE REVIEW

**Comment by Aishh2k** [comment]
@plxity Okay! I have done that! Please review!

**Comment by plxity** [comment]
@Aishh2k Already this feature is present in the footer of the page. Please check it. I don't think we need a separate button for that.

**Comment by plxity** [comment]
@Aishh2k Okay, I got your point. 
Let's see what @mariobehling  suggests on implementing this feature?

**Comment by Aishh2k** [comment]
@plxity Okay cool! :)

**Comment by Aishh2k** [comment]
@mariobehling

**Comment by mariobehling** [comment]
Please see my comment here. Thanks: https://github.com/fossasia/labs.fossasia.org/issues/338#issuecomment-456085949

**Pull request closed without merging**
