### PR TITLE
Added smooth scroll behaviour

### PR DESCRIPTION
**Pull request by Dishebh**
Fix for issue #396 

Added the inner-link smooth-scrolling effect for the web-page.

### CODE REVIEW

**Comment by Dishebh** [comment]
@mariobehling pls have a look at the PR, see if it solves the issue?

**Comment by Dishebh** [comment]
@mariobehling here's the preview link:
https://dishebh.github.io/labs.fossasia.org/

**Comment by Chaitanyassr** [comment]
the scrolling is slow for first 1sec and than its move up fast very quickly.

**Comment by Chaitanyassr** [comment]
@mariobehling Sir , I have solved this issue, can you please check ones and please tell if it meant your requirements. I m creating an another pull request.

**Comment by Chaitanyassr** [comment]
@mariobehling  Sir, I have solved this issue. please check and tell if that is what you need.
i have created another pull request for it.
thank you.

**Pull request closed without merging**
