### PR TITLE
Added Hover-over text for better navigation !! (Issue no. #259 fixed :D)

### PR DESCRIPTION
**Pull request by Beta-King**
You can find the changes in the footer region :D 
#259 , i've fixed this issue !!

### CODE REVIEW

**Comment by Beta-King** [comment]
https://beta-king.github.io/veronicaalabs.fossasia.org/ --> Preview Link !!

**Comment by Beta-King** [comment]
Please review and merge :D

**Comment by Beta-King** [comment]
??

**Comment by abishekvashok** [comment]
Waiting for an admin to take note of this.

**Comment by Beta-King** [comment]
Guys ?? :D

**Comment by Beta-King** [comment]
Yeah sure :D

**Comment by Beta-King** [comment]
Added issue number to the PR :D

**Comment by Beta-King** [comment]
please review and merge :D

**Comment by Beta-King** [comment]
could you also approve my task on GCI :D

**Pull request merged**
