### PR TITLE
Update idea section color

### LINKED ISSUE #392: Website: Change the gray color of the ideas section to match the "Connect to FOSSASIA" section
The gray background of the ideas section is slightly darker than other areas, e.g. "Connect to FOSSASIA".

Please adjust the background color to the same slightly lighter gray.

Screenshot from 2019-12-13 13-37-19
Screenshot from 2019-12-13 12-47-01

### PR DESCRIPTION
**Pull request by huonggiangbui**
Fixes #392

### CODE REVIEW

**Comment by mariobehling** [comment]
Please provide a link to a test site.

**Comment by huonggiangbui** [comment]
Preview link: huonggiangbui.github.io/labs.fossasia.org

**Comment by mariobehling** [comment]
Please check your own preview link. You will see issues right away.

**Comment by huonggiangbui** [comment]
I changed the background color in idea section as well as footer background color, and it is much lighter. The issue didnt fixed?

**Comment by huonggiangbui** [comment]
Check it again please, the color has changed

**Comment by anishagg17** [comment]
bro how did you deployed this pr.
Actually i am facing error   "The CNAME labs.fossasia.org is already taken"

**Comment by huonggiangbui** [comment]
You should wait about 30mins to 1 hour, and check your page again (with your link: username.github.io/labs.fossasia.org). I couldnt see my page 2 hours ago and now I can get it

**Comment by anishagg17** [comment]
thanks bro

**Comment by anishagg17** [comment]
Screenshot 2019-12-13 at 8 48 56 PM
@huonggiangbui we didn't wanted to change the colour of header .Only the colour of ideas body was supposed to be changed

**Comment by huonggiangbui** [comment]
I changed the background color of table id and div element with results-projects only lol

**Pull request closed without merging**
