### PR TITLE
Added Badge Magic to Projects

### PR DESCRIPTION
**Pull request by adityastic**
Screenshot for Change:
Screenshot 2019-06-21 at 3 18 51 PM

### CODE REVIEW

**Comment by adityastic** [comment]
@mariobehling review

**Comment by mariobehling** [comment]
Please take out the last sentence "based on the work...".

**Comment by adityastic** [comment]
> Please take out the last sentence "based on the work...".

got it

**Comment by adityastic** [comment]
updated @mariobehling 
Screenshot 2019-06-22 at 8 13 36 AM

**Comment by mariobehling** [comment]
Please provide a link to your test gh pages site.

**Comment by adityastic** [comment]
@mariobehling sure

**Comment by adityastic** [comment]
@mariobehling updated pages link, plz merge

**Pull request merged**
