### PR TITLE
Replaced the image by SUSI.AI Official Logo. Issue #262 resolved.

### PR DESCRIPTION
**Pull request by PulkitMishra**
I have made the specified changes. Please check if the resolution is appropriate.

### CODE REVIEW

**Comment by abishekvashok** [comment]
For reviewers: https://PulkitMishra.github.io/labs.fossasia.org

**Comment by anshumanv** [comment]
I was thinking if there can be a better image than this, perhaps showing some chats from the webapp?

**Comment by rupav** [comment]
@anshumanv do you want changes, if not please merge this PR.

**Comment by mariobehling** [comment]
This is just an image of a SUSI.AI web client. So, this image could be updated with a newer version. It should not be exchanged with the "S" of the logo only. Therefore closing it.

**Pull request closed without merging**
