### PR TITLE
ExpEYES Pocket Science Lab

### PR DESCRIPTION
**Pull request by wavicles**
Links fixed

### CODE REVIEW

**Comment by samarjeet27** [comment]
@wavicles please add the category "ExpEYES Science Lab" to ideas.md

**Comment by wavicles** [comment]
Hi Samarjeet
On Tue, Mar 24, 2015 at 8:54 PM, Samarjeet <notifications@github.com> wrote:

> @wavicles <https://github.com/wavicles> please add the category "ExpEYES
> Science Lab" to ideas.md
>

I think I have added it. Please check and rectify if needed.
Thanks
Praveen

**Comment by samarjeet27** [comment]
Oh great :)

**Comment by wavicles** [comment]
Thanks a lot.

**Pull request merged**
