### PR TITLE
Add table to project category

### PR DESCRIPTION
**Pull request by samarjeet27**

### CODE REVIEW

**Comment by mariobehling** [comment]
a) Please get rid of list points
screenshot from 2015-03-18 14 09 30
b) Please create a "table of contents"

**Comment by mariobehling** [comment]
What is a table of contents. Please see below.
screenshot from 2015-03-18 14 13 03

**Comment by samarjeet27** [comment]
@mariobehling what do you mean by 'table of contents' here ?

**Comment by mariobehling** [comment]
Add all projects on top in a table of contents and link (anchor) to the project within the page.

**Comment by samarjeet27** [comment]
@mariobehling , so an internal link ?

**Comment by mariobehling** [comment]
yes.

**Comment by mariobehling** [comment]
and it looks like you are keeping empty lists. there. please delete the list points.

**Comment by mariobehling** [comment]
actually, if you could fix the list points first, would be great. It makes the site difficult to read.

**Comment by samarjeet27** [comment]
got rid of the bullets in https://github.com/fossasia/labs.fossasia.org/pull/51

**Comment by mariobehling** [comment]
thanks. Now do not "indent" all text. No need for indention.
screenshot from 2015-03-18 14 38 53

**Pull request merged**
