### PR TITLE
favicon icon and GSoC projects

### PR DESCRIPTION
**Pull request by todipratik**

### CODE REVIEW

**Comment by eMBee** [comment]
great! please rebase your changes instead of merging.

student and links should be listed in the project pages themselves too.
it probably makes sense to reuse the include.

**Comment by todipratik** [comment]
by rebasing, do you mean to create a new branch ?

which project pages should contain student and links ?

**Comment by eMBee** [comment]
well, rebasing means moving your current branch on top of the main branch
the pages you added.

btw: take a look at #22, instead of adding the fields manually in each project, use a template. keep in mind my comments there however and create a new template, don't modify the index template.

**Comment by todipratik** [comment]
Sorry @eMBee. Still, couldn't get you. Initially their were fields like **skills**, **skills-level** in template (post_detail.html). I think I have added only project links and student field in template. Now which new template needs to be created?

And I didn't create any new branch for adding the project pages. I did it in **gh-pages** itself. The commits for the same are on top. The following is a screenshot as shown by **git log**
screenshot from 2015-02-18 09 52 06

**Comment by eMBee** [comment]
see the current solution, it implements what i meant. 

on the branch rebase topic, watch closely how the history of your commits now connects to the branch.

**Pull request closed without merging**
