### PR TITLE
Add new header image

### PR DESCRIPTION
**Pull request by Ploypiti**
Add new header image (original: img/hero7) #243 
[preview link here](https://ploypiti.github.io/labs.fossasia.org/)

### CODE REVIEW

**Comment by vaibhavsingh97** [comment]
@Ploypiti Can you please share some screenshots what change you are reffering to. Also, after your changes it's deficylt to see the nav

**Comment by Ploypiti** [comment]
@vaibhavsingh97 I'm not sure why it didn't work in the live preview, here's how it should look like:
image

**Comment by vaibhavsingh97** [comment]
@Ploypiti It's because `theme-lava.css` file contains these properties and beacuse of that your background image is not working.

```css
.background-image-holder img {
    display: none;
}
```

**Comment by Ploypiti** [comment]
P.S. None of the image displayed on my side, is it because the theme or something's wrong with my Repo.

**Comment by vaibhavsingh97** [comment]
@Ploypiti You have to edit this
```html
<div class="background-image-holder parallax-background skrollable skrollable-between" style="background: rgba(0, 0, 0, 0) url(&quot;img/hero7.jpg&quot;) repeat scroll 50% 0%; transform: translate3d(0px, 3.22581px, 0px);" data-bottom-top="-moz-transform: translate3d(0px,-100px, 0px)" data-center="-moz-transform: translate3d(0px,0px, 0px)" data-top-bottom="-moz-transform: translate3d(0px,100px, 0px)">
<img class="background-image" alt="Background Image" src="img/hero7.jpg" style="display: none;">
</div>
```

**Comment by akshatnitd** [comment]
@Ploypiti The demo link you shared gives 404 error.

**Comment by abishekvashok** [comment]
She must have delete her fork.

**Comment by Ploypiti** [comment]
@akshatnitd Can you please try again with the same link, also is there any way I could load the font & images on my repo since it didn't work, as I mentioned.

**Comment by Ploypiti** [comment]
@akshatnitd Please try again with the same link, it's the rename thing.

**Comment by akshatnitd** [comment]
@Ploypiti Check the demo link. I guess the problem occurs since the scripts are not loaded over ```https```.

Change the script tags source to https and it should work. I can see the blocked script error for jquery as well as the fonts. Check the developer console.
screenshot from 2017-12-16 16-26-15

**Comment by Ploypiti** [comment]
@akshatnitd It worked :tada:

**Comment by akshatnitd** [comment]
@Ploypiti Please try to squash the commits from next time :+1:

**Pull request merged**
