### PR TITLE
Aligned Links in Projects Sections

### LINKED ISSUE #299: Links Are Not Aligned
The links in the following sections are not lined up.

screen shot 2018-10-31 at 9 49 22 pm
screen shot 2018-10-31 at 9 49 09 pm

I will work on this.

### PR DESCRIPTION
**Pull request by Ryan10145**
Fixes #299 

Aligned the links in the Fossasia Projects and How Can I Join projects Section.

screen shot 2018-11-01 at 5 39 21 pm
screen shot 2018-11-01 at 5 39 31 pm
screen shot 2018-11-01 at 5 40 00 pm
screen shot 2018-11-01 at 5 40 07 pm

Testing Link: https://ryan10145.github.io/labs.fossasia.org/

### CODE REVIEW

**Comment by AakashMallik** [comment]
@Ryan10145 Actually those divs don't have any kind of differentiating border and hence those newly aligned links look kind of out of place. Don't you think so?

**Comment by Ryan10145** [comment]
@AakashMallik Perhaps the margins on those sections can be updated in order to make associating the links easier. Perhaps 

Here are some screenshots with those margins edited:

# Images
Image 1 Before:

screen shot 2018-10-31 at 9 49 22 pm

Image 1 After:
image

Image 2 Before:
screen shot 2018-10-31 at 9 49 09 pm

Image 2 After:
image


Let me know if you disagree or have any other ideas.

**Comment by Ryan10145** [comment]
I've changed the margins as indicated above. Hopefully this makes the links a bit easier to associate with the text above them.

image
image

**Comment by AakashMallik** [comment]
Yeah that looks great. Good call on making changes with the margin.

**Comment by AakashMallik** [comment]
@Ryan10145 Please check if the result are consistent on all types of screens. ( Responsive ) Let me know what you find out.

**Comment by Ryan10145** [comment]
@AakashMallik I've updated the spacing a bit because on extremely narrow screen sizes, the text would overlap.


Mobile:
image


Tablet:
image


Desktop:
image



Mobile:
image


Tablet:
image


Desktop:
image

**Comment by AakashMallik** [comment]
Well done

**Comment by mariobehling** [comment]
Actually, there is no need to align the links. The distance should rather not be too big to the text description. Thanks.

**Pull request merged**
