### PR TITLE
Navigate to correct area

### LINKED ISSUE #376: Website: GitHub API generated links don't direct to the right area anymore
Clicking on the link list of the GSoC ideas does not direct to the correct area on https://labs.fossasia.org.

Screenshot from 2019-12-12 12-48-33

### PR DESCRIPTION
**Pull request by huonggiangbui**
Fixes #376

### CODE REVIEW

**Comment by anishagg17** [comment]
Bro i have already submitted a pull request to fix it , this issue is assigned to me

**Comment by huonggiangbui** [comment]
> Bro i have already submitted a pull request to fix it , this issue is assigned to me

This is the GCI task which I claimed, and I need to fix this issue. I think it is open to everyone, not only you. Moreover, I think that your changed codes dont fix this issue anymore.

**Comment by mariobehling** [comment]
Oh , my mistake. It does not seem to solve the issue. Have to revert it.

**Comment by mariobehling** [comment]
Please follow up here: https://github.com/fossasia/labs.fossasia.org/issues/386

**Comment by huonggiangbui** [comment]
> Oh , my mistake. It does not seem to solve the issue. Have to revert it.

really? can you check it again please? I tried it on my own code (sorry because I try to host the changed code on Github page but it show error page) and when I click the idea section it goes to the idea below

**Pull request merged**
