### PR TITLE
Adds showdown support for markdown => html for issue #89

### PR DESCRIPTION
**Pull request by sopu**
Improves readability of gsoc ideas.

### CODE REVIEW

**Comment by mananwason** [comment]
Hey @sopu Could you push to your gh-pages. Thanks!

**Comment by sopu** [comment]
Sure @mananwason

**Comment by mananwason** [comment]
great :+1:

**Comment by sopu** [comment]
Done!
@mananwason should I add a PR from that branch.

**Comment by mananwason** [comment]
Yeah. Go ahead. It's always recommended to create PR's from gh-pages branch.

**Comment by sopu** [comment]
Thanx for suggesting that. Will keep in mind :+1:

**Pull request closed without merging**
