### PR TITLE
add Meta tags; closes #303

### LINKED ISSUE #303: Add SEO Meta Tags
Add The following meta tags for SEO
- Apple
- Facebook
I would Like to work on this

### PR DESCRIPTION
**Pull request by pythongiant**
Add Meta Tags for better SEO

### CODE REVIEW

**Comment by pythongiant** [comment]
Doesnt seem like  the travis check is my fault

**Comment by Ryan10145** [comment]
@pythongiant Pull changes to your fork so that the travis build errors are fixed.

**Comment by pythongiant** [comment]
@Ryan10145 haha! I was the person who fixed the travis check. Does it matter?

**Comment by pythongiant** [comment]
@jogendra a little SEO wouldn't here would it?

**Comment by Ryan10145** [comment]
@pythongiant You fixed the build errors in another PR, but you never pulled those chanegs to this PR, which means the travis check fails as a result of that. It matters because those issues are causing the travis build to fail, and they should be fixed so that the travis build can continue and possibly reveal if there are any further build errors currently unknown.

**Comment by pythongiant** [comment]
@Ryan10145 there's absolutely nothing in the PR that would make the build fail.

**Comment by Ryan10145** [comment]
@pythongiant Just to verify, you should fix the travis build by pulling changes to your repo. It's better to be safe than to accidentally break the website.

**Pull request merged**
