### PR TITLE
update grey color

### LINKED ISSUE #392: Website: Change the gray color of the ideas section to match the "Connect to FOSSASIA" section
The gray background of the ideas section is slightly darker than other areas, e.g. "Connect to FOSSASIA".

Please adjust the background color to the same slightly lighter gray.

Screenshot from 2019-12-13 13-37-19
Screenshot from 2019-12-13 12-47-01

### PR DESCRIPTION
**Pull request by huonggiangbui**
Fixes #392 
Preview link: https://huonggiangbui.github.io/labs.fossasia.org/

### CODE REVIEW

**Comment by mariobehling** [comment]
Your changes resulted in the social media section not being gray anymore and the red colored section has a kind of line somehow.

Screenshot from 2019-12-13 20-35-09

**Comment by mariobehling** [comment]
Oh, it seems the issue with the red line got in a bit earlier. Need to check where that change happened.

**Comment by mariobehling** [comment]
Ok, the gray color thing is fixed now. Please try another issue. Please try to check your changes in detail to ensure things can progress quickly. Thanks!

**Comment by huonggiangbui** [comment]
@mariobehling did you merged my commit? I see that the PR and isue were closed but the PR seemed not merged yet

**Comment by mariobehling** [comment]
I took care of it. Unfortunately your code was not working as expected. Please try more at follow up tasks.

**Pull request closed without merging**
